package huma

// registry.go — the read-write humav2.Registry bridge.
//
// wireleaf is the schema authority: huma keeps no schema map of its own. Every schema huma asks for is answered from the shared
// apidoc.Components — either a component wireleaf already owns, or one produced
// on demand by the canonical reflector and registered INTO the shared set. That
// is what makes huma-originated types (ErrorModel, input structs, nested body
// types) part of the same document as the graph-derived components.
//
// The shared set holds TYPED IR on both sides of the bridge: components enter
// through apidoc.Components.RegisterReflected (which owns idempotence — an
// identical re-registration is a no-op, a conflicting one an error) and are read
// back through Components.Get. There is no bridge-side shadow of the entries and
// no map round trip in either direction.
//
// BOUNDARY IDIOM — non-struct types. A type wireleaf does not model as a
// component (a scalar, slice, map, time.Time, url.URL, or anything providing its
// own schema) is generated by huma's own SchemaFromType, recursing back through
// this bridge so nested component-worthy types still land in the shared set.
// That path is huma's, not wireleaf's, and it differs in places: a top-level
// []T body is NULLABLE under huma's DefaultArrayNullable, whereas a []T STRUCT
// FIELD goes through the canonical reflector and the wireleaf nullability
// policy. The divergence is confined to the top level of a non-struct body.
//
// LIMITATION — huma's registryConfig (Config.AllowAdditionalPropertiesByDefault,
// Config.FieldsOptionalByDefault) is applied by huma only to its own
// *mapRegistry, so both options are silently INERT against this bridge:
// additional-properties and required-ness are the canonical reflector's verdict,
// and NewConfig exposes neither option.
//
// NOTE — the canonical reflector deliberately does NOT emit
// "additionalProperties": false, while stock huma does for structs. A body
// validated by wireleaf's components therefore accepts unknown properties where
// stock huma would have rejected them. That is canon, not an oversight.

import (
	"encoding"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"sort"
	"strings"
	"sync"
	"time"

	humav2 "github.com/danielgtaylor/huma/v2"

	"github.com/qrotux/wireleaf/apidoc"
)

var (
	timeType            = reflect.TypeFor[time.Time]()
	urlType             = reflect.TypeFor[url.URL]()
	schemaProviderType  = reflect.TypeFor[humav2.SchemaProvider]()
	textUnmarshalerType = reflect.TypeFor[encoding.TextUnmarshaler]()
)

// Registry bridges huma's schema registry onto a shared apidoc.Components plus
// the canonical reflector.
//
// CONCURRENCY. Registration (Schema, RegisterTypeAlias) happens at startup
// wiring time and is NOT safe to run concurrently with itself. Serving is not
// read-only, though: SchemaFromRef is on huma's request-validation path and
// populates a lazy conversion cache, so it can run from many request goroutines
// at once. The maps it touches — converted (written by schemaFor) and types
// (read by TypeFromRef) — are therefore guarded by mu. aliases is
// registration-time only (written by RegisterTypeAlias, read by Schema) and
// stays unguarded, as does the shared *apidoc.Components, which is likewise
// only written during wiring and only read while serving.
type Registry struct {
	c *apidoc.Components
	r apidoc.Reflector

	// mu guards converted and types — the two maps that a request-time
	// SchemaFromRef can reach. See the CONCURRENCY note above.
	mu sync.RWMutex

	// types is the component name → owning Go type index behind TypeFromRef. It
	// covers everything THIS bridge registered, auxiliaries included;
	// application-registered components are found through the shared index
	// instead (Components.TypeOf). GUARDED by mu: written at registration time,
	// read on the request path through schemaFor.
	types map[string]reflect.Type
	// aliases implements RegisterTypeAlias. UNGUARDED: registration-time only.
	aliases map[reflect.Type]reflect.Type
	// converted caches the huma form per component name — SchemaFromRef is on
	// huma's request-validation hot path. A component's content never changes
	// once registered (Add rejects a duplicate, RegisterReflected requires an
	// identical IR), so the cache needs no invalidation. GUARDED by mu: this is
	// the one map written while serving.
	converted map[string]*humav2.Schema
}

var (
	_ humav2.Registry = (*Registry)(nil)
	_ json.Marshaler  = (*Registry)(nil)
)

// NewRegistry returns the bridge over c and r. Both are required.
func NewRegistry(c *apidoc.Components, r apidoc.Reflector) humav2.Registry {
	if c == nil {
		panic("adapters/huma: NewRegistry: nil Components")
	}
	if r == nil {
		panic("adapters/huma: NewRegistry: nil Reflector")
	}
	return &Registry{
		c:         c,
		r:         r,
		types:     map[string]reflect.Type{},
		aliases:   map[reflect.Type]reflect.Type{},
		converted: map[string]*humav2.Schema{},
	}
}

// Components exposes the shared component set the bridge writes into.
func (b *Registry) Components() *apidoc.Components { return b.c }

// ---------------------------------------------------------------------------
// humav2.Registry
// ---------------------------------------------------------------------------

// Schema answers huma's schema request for t. Order matters:
//  1. a type registered through RegisterTypeAlias resolves as its alias
//     (the lookup recurses, so the alias walks the rest of this list);
//  2. a node WRAPPER type resolves to the component its wire type owns;
//  3. a type already bound to a component name resolves to that component;
//  4. a struct matching the success-envelope convention (envelope.go) is
//     DERIVED as an envelope — before any reflection, so the document describes
//     the envelope rather than the Go field shape;
//  5. a type wireleaf does not model as a component is generated inline by huma
//     itself — see the boundary-idiom note at the top of this file;
//  6. anything else is reflected through the canonical reflector and every
//     component it returns (the top AND the auxiliaries) is registered.
//
// A reflection or registration failure PANICS: this runs at startup wiring
// time, where a half-built document is worse than a loud stop.
func (b *Registry) Schema(t reflect.Type, allowRef bool, hint string) *humav2.Schema {
	orig := t
	t = apidoc.DerefType(t)
	if t == nil {
		panic("adapters/huma: Registry.Schema: nil type")
	}
	if alias, ok := b.aliases[t]; ok {
		return b.Schema(alias, allowRef, hint)
	}
	if name, ok := b.c.NodeComponent(t); ok {
		return b.answer(name, allowRef)
	}
	if name, ok := b.c.TypeName(t); ok {
		return b.answer(name, allowRef)
	}
	// The success-envelope data convention (envelope.go) is checked BEFORE the
	// canonical reflection: a body struct matching it documents an envelope,
	// not its Go field shape. Everything else falls through untouched.
	if ir, ok := b.envelopeIR(t, hint); ok {
		return b.answer(b.registerDerived(t, hint, ir), allowRef)
	}
	if !componentWorthy(t) {
		return humav2.SchemaFromType(b, orig)
	}
	return b.answer(b.reflectAndRegister(t, hint), allowRef)
}

// SchemaFromRef resolves a "#/components/schemas/X" reference. It is on huma's
// request-validation hot path, so the conversion is cached.
func (b *Registry) SchemaFromRef(ref string) *humav2.Schema {
	if !strings.HasPrefix(ref, apidoc.RefPrefix) {
		return nil
	}
	return b.schemaFor(strings.TrimPrefix(ref, apidoc.RefPrefix))
}

// TypeFromRef is the inverse index: the Go type a component was registered for,
// or the zero reflect.Type when it has none (an auxiliary the reflector named on
// its own, or a component assembled by hand).
//
// It consults the SHARED type index as well as the bridge's own, so a component
// the application registered together with its wire type (RegisterType, or
// RegisterNode's binding of W) answers here too. huma builds a Go struct type
// from this when it serves a response body, so an answer that exists must be
// found — see schemaFor for what happens when none does.
func (b *Registry) TypeFromRef(ref string) reflect.Type {
	name := strings.TrimPrefix(ref, apidoc.RefPrefix)
	b.mu.RLock()
	t, ok := b.types[name]
	b.mu.RUnlock()
	if ok {
		return t
	}
	if t, ok := b.c.TypeOf(name); ok {
		return t
	}
	return nil
}

// Map renders the WHOLE shared component set — the bridge's own registrations
// and everything the application registered directly — in huma form. The map is
// rebuilt per call from the live Components; mutating it does not write back.
func (b *Registry) Map() map[string]*humav2.Schema {
	out := map[string]*humav2.Schema{}
	for _, name := range b.names() {
		if s := b.schemaFor(name); s != nil {
			out[name] = s
		}
	}
	return out
}

// RegisterTypeAlias makes the bridge answer for t as if it were alias.
func (b *Registry) RegisterTypeAlias(t reflect.Type, alias reflect.Type) {
	b.aliases[apidoc.DerefType(t)] = alias
}

// MarshalJSON serves the components/schemas object of the document: huma
// marshals Components.Schemas through this. It agrees with Map by construction,
// which matters because huma's unused-schema pruning marshals Map's result
// directly instead.
func (b *Registry) MarshalJSON() ([]byte, error) { return json.Marshal(b.Map()) }

// MarshalYAML mirrors mapRegistry's. huma's own YAML path goes through JSON, so
// nothing in huma calls this; it exists so the bridge is a drop-in for code that
// marshals a registry with a YAML encoder.
func (b *Registry) MarshalYAML() (any, error) { return b.Map(), nil }

// ---------------------------------------------------------------------------
// registration
// ---------------------------------------------------------------------------

// reflectAndRegister reflects t through the canonical reflector and registers
// every component it produced. Returns the top component's name.
func (b *Registry) reflectAndRegister(t reflect.Type, hint string) string {
	b.assertNoNodeWrappers(t)
	name := componentName(t, hint)
	comps, err := b.r.ReflectComponents([]reflect.Type{t}, map[reflect.Type]string{t: name})
	if err != nil {
		panic(fmt.Sprintf("adapters/huma: reflecting %v into component %q: %v", t, name, err))
	}
	if _, ok := comps[name]; !ok {
		// The usual cause is an ANONYMOUS struct: the reflection engine inlines
		// a root anonymous struct instead of defining it, so the requested name
		// is never produced. Naming the type is the fix, and the message says so
		// rather than leaving a caller to infer it from a missing key.
		panic(fmt.Sprintf("adapters/huma: reflector did not return the requested component %q for %v "+
			"(an anonymous struct cannot be reflected into a component — use a named body type)", name, t))
	}
	names := make([]string, 0, len(comps))
	for n := range comps {
		names = append(names, n)
	}
	sort.Strings(names) // deterministic error on a conflicting set

	// Every component gets its owning Go type, auxiliaries included. huma needs
	// the type back for any component it serves as a response body (see
	// schemaFor), and an auxiliary here is just a nested struct that another
	// operation may well use as a body of its own.
	owners := auxTypes(t)
	for _, n := range names {
		owner := owners[n]
		if n == name {
			owner = t // the requested type owns the requested name, whatever it is called
		}
		if err := b.c.RegisterReflected(n, comps[n], owner); err != nil {
			panic(fmt.Sprintf("adapters/huma: registering component %q for %v: %v", n, t, err))
		}
		if owner != nil {
			b.mu.Lock()
			b.types[n] = owner
			b.mu.Unlock()
		}
	}
	return name
}

// assertNoNodeWrappers is a LOUD startup guard on the reflection path.
//
// A node wrapper carries its payload in an unexported field: the canonical
// reflector, which knows nothing about nodes, sees a struct with zero exported
// fields and emits an empty object. That is a silently wrong contract — the
// document would promise {} where the engine sends a whole resource — so a
// wrapper reached from a type on its way to the reflector STOPS the wiring
// instead.
//
// A node legitimately appears only where the bridge itself resolves it: as an
// envelope's data field (envelope.go's convention), as an open-page extra field
// routed back through Schema, or as a body type of its own (which never reaches
// here — the NodeComponent lookup in Schema answers first).
//
// SCOPE: the walk is transitive, so an ENVELOPE nested inside a plain struct
// panics too. That is deliberate. Reached as a field, an envelope struct is
// reflected as an ordinary struct (the derivation runs on the type the bridge is
// ASKED for, not on the types it walks into), so the document would promise
// {data:{}} — the same silent lie, one level down. Compose envelopes at the body
// type, not inside one.
func (b *Registry) assertNoNodeWrappers(root reflect.Type) {
	seen := map[reflect.Type]bool{}
	var walk func(reflect.Type)
	walk = func(cur reflect.Type) {
		cur = apidoc.DerefType(cur)
		if cur == nil || seen[cur] {
			return
		}
		seen[cur] = true
		switch cur.Kind() {
		case reflect.Slice, reflect.Array, reflect.Map:
			walk(cur.Elem())
		case reflect.Struct:
			for i := range cur.NumField() {
				f := cur.Field(i)
				if !f.IsExported() || f.Tag.Get("json") == "-" {
					continue
				}
				if wrapper, ok := b.nodeWrapperIn(f.Type); ok {
					panic(fmt.Sprintf(
						"adapters/huma: node wrapper %v reached the canonical reflector via %v.%s; "+
							"nodes may only appear as an envelope data field (or an open-page extra routed through the bridge)",
						wrapper, cur, f.Name))
				}
				walk(f.Type)
			}
		}
	}
	walk(root)
}

// nodeWrapperIn unwraps pointers, slices, arrays and maps down to the value
// type and reports whether it is a registered node wrapper.
func (b *Registry) nodeWrapperIn(t reflect.Type) (reflect.Type, bool) {
	for {
		t = apidoc.DerefType(t)
		if t == nil {
			return nil, false
		}
		if _, ok := b.c.NodeComponent(t); ok {
			return t, true
		}
		switch t.Kind() {
		case reflect.Slice, reflect.Array, reflect.Map:
			t = t.Elem()
		default:
			return nil, false
		}
	}
}

// registerDerived registers a DERIVED component (a success envelope) under the
// name huma's namer gives t, bound to t so the bridge serves it typed and huma
// can build the Go type back from the $ref. The binding also short-circuits the
// derivation on the next request for t: the TypeName lookup in Schema answers
// first.
func (b *Registry) registerDerived(t reflect.Type, hint string, ir *apidoc.IRNode) string {
	name := componentName(t, hint)
	if err := b.c.RegisterReflected(name, ir, t); err != nil {
		panic(fmt.Sprintf("adapters/huma: registering derived component %q for %v: %v", name, t, err))
	}
	b.mu.Lock()
	b.types[name] = t
	b.mu.Unlock()
	return name
}

// auxTypes walks t's wire shape and indexes the struct types it reaches under
// the names the canonical reflector gives them (the Go type name — see the
// reflector's defName). It is how an auxiliary component gets its owning type
// back: ReflectComponents returns names and IR, not types.
//
// A type the reflector would not turn into a component of its own
// (time.Time, a SchemaProvider, …) is skipped — approximately as it is skipped
// there: componentWorthy is huma's rule, not the reflector's, and the two
// differ on url.URL, humav2.SchemaProvider and encoding.TextUnmarshaler. The
// consequence of a disagreement is a missing owner type for an auxiliary, which
// degrades that component to opaque serving (see schemaFor), never a wrong one.
func auxTypes(t reflect.Type) map[string]reflect.Type {
	out := map[string]reflect.Type{}
	seen := map[reflect.Type]bool{}
	var walk func(reflect.Type)
	walk = func(cur reflect.Type) {
		cur = apidoc.DerefType(cur)
		if cur == nil || seen[cur] {
			return
		}
		seen[cur] = true
		switch cur.Kind() {
		case reflect.Slice, reflect.Array:
			walk(cur.Elem())
		case reflect.Map:
			walk(cur.Elem())
		case reflect.Struct:
			if !componentWorthy(cur) {
				return
			}
			if n := cur.Name(); n != "" {
				if _, taken := out[n]; !taken {
					out[n] = cur
				}
			}
			for i := range cur.NumField() {
				f := cur.Field(i)
				if !f.IsExported() || f.Tag.Get("json") == "-" {
					continue
				}
				walk(f.Type)
			}
		}
	}
	walk(t)
	return out
}

// ---------------------------------------------------------------------------
// reading the shared set
// ---------------------------------------------------------------------------

// names returns every component name in the shared set, sorted. apidoc.Merge is
// the only exported enumeration seam over a Components; it is used HERE ONLY —
// on the document-emission path, never per registration or per request.
func (b *Registry) names() []string {
	scratch := map[string]any{}
	if err := b.c.Merge(scratch); err != nil {
		panic(fmt.Sprintf("adapters/huma: reading components: %v", err))
	}
	out := make([]string, 0, len(scratch))
	for name := range scratch {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// schemaFor converts one component to huma form, cached.
//
// SERVING RULE: a component is served TYPED — the full converter, so huma both
// documents and VALIDATES it — only when its Go wire type is known and is a
// struct. Otherwise it is served through the Extensions bridge, as one opaque
// fragment.
//
// The reason is huma's SchemaLinkTransformer (installed by DefaultConfig). For
// every response body whose schema has "type":"object" it builds a wrapper Go
// struct out of deref(registry.TypeFromRef(ref)) and reads its fields
// (transforms.go:110) — with no nil check, and outside its own recover(). A
// component with no wire type can NEVER satisfy TypeFromRef, so serving it typed
// in response position is a guaranteed panic at huma.Register. Serving it opaque
// leaves Type == "", which makes the transformer bail one line earlier and skip
// it. The same holds for a component bound to a non-struct type: NumField would
// panic on the very same line.
//
// The served document is byte-identical either way.
//
// CONCURRENCY: the cache is read and written under mu; the conversion itself
// runs unlocked over the immutable IR, and a racing duplicate is resolved on
// insert so every caller for a name gets the same *humav2.Schema pointer.
func (b *Registry) schemaFor(name string) *humav2.Schema {
	b.mu.RLock()
	s, ok := b.converted[name]
	b.mu.RUnlock()
	if ok {
		return s
	}
	entry, ok := b.c.Get(name)
	if !ok {
		return nil
	}
	if servableAsType(b.TypeFromRef(apidoc.RefPrefix + name)) {
		var err error
		if s, err = toHuma(entry.IR()); err != nil {
			panic(fmt.Sprintf("adapters/huma: converting component %q: %v", name, err))
		}
	} else {
		s = opaqueSchema(name, entry.IR())
	}
	b.mu.Lock()
	defer b.mu.Unlock()
	if prev, ok := b.converted[name]; ok {
		return prev // a concurrent caller won the race; one schema per name
	}
	b.converted[name] = s
	return s
}

// servableAsType reports whether huma's response-body machinery can build a
// wrapper struct from t.
func servableAsType(t reflect.Type) bool {
	return apidoc.DerefType(t) != nil && apidoc.DerefType(t).Kind() == reflect.Struct
}

// opaqueSchema renders a component as one Extensions-bridge fragment: a zero
// typed Schema whose Extensions hold the whole thing marshals to exactly it.
func opaqueSchema(name string, n *apidoc.IRNode) *humav2.Schema {
	raw, err := n.MarshalJSON()
	if err != nil {
		panic(fmt.Sprintf("adapters/huma: serializing component %q: %v", name, err))
	}
	var m map[string]any
	if err := json.Unmarshal(raw, &m); err != nil {
		panic(fmt.Sprintf("adapters/huma: component %q is not a JSON object: %v", name, err))
	}
	s := &humav2.Schema{Extensions: m}
	s.PrecomputeMessages()
	return s
}

// answer returns either a reference to the named component or its full schema.
func (b *Registry) answer(name string, allowRef bool) *humav2.Schema {
	if allowRef {
		return &humav2.Schema{Ref: apidoc.RefPrefix + name}
	}
	return b.schemaFor(name)
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// componentWorthy reports whether t is a type wireleaf renders as a NAMED
// component. It follows huma's own getsRef rule so the two registries agree on
// what earns a $ref, and it keeps non-struct types away from the reflector,
// which only reflects structs.
//
// It is huma's rule, so it matches the canonical reflector's notion of a
// definition only APPROXIMATELY: url.URL, humav2.SchemaProvider implementors
// and encoding.TextUnmarshaler implementors are excluded here on huma's
// authority, and the reflector may or may not treat them the same way.
func componentWorthy(t reflect.Type) bool {
	if t.Kind() != reflect.Struct || t == timeType || t == urlType {
		return false
	}
	pt := reflect.PointerTo(t)
	for _, iface := range []reflect.Type{schemaProviderType, textUnmarshalerType} {
		if t.Implements(iface) || pt.Implements(iface) {
			return false
		}
	}
	return true
}

// componentName is huma's naming rule, which agrees with the reflector's own
// default (the Go type name) for ordinary named structs and supplies huma's
// hint-derived name for anonymous ones.
func componentName(t reflect.Type, hint string) string {
	return humav2.DefaultSchemaNamer(t, hint)
}
