package apidoc

import (
	"fmt"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// ---------------------------------------------------------------------------
// property access
// ---------------------------------------------------------------------------

// object returns the underlying node, panicking unless it is an object — every
// delta below targets an object schema produced by a Reflector or a literal.
func (s Schema) object() *IRNode {
	if s.n == nil || s.n.Kind != KindObject {
		panic(fmt.Sprintf("apidoc: schema has no properties map (fragment: %v)", s.Map()))
	}
	return s.n
}

// propNames returns the receiver's property names, sorted (panic messages must
// be stable regardless of Props order).
func (s Schema) propNames() []string {
	n := s.object()
	names := make([]string, 0, len(n.Props))
	for _, p := range n.Props {
		names = append(names, p.Name)
	}
	sort.Strings(names)
	return names
}

// mustProp panics unless key exists in properties — a typo in a delta must be
// an instant unit-test failure, never a silent no-op.
func (s Schema) mustProp(key string) *Prop {
	n := s.object()
	for i := range n.Props {
		if n.Props[i].Name == key {
			return &n.Props[i]
		}
	}
	panic(fmt.Sprintf("apidoc: unknown property %q in schema (have %v)", key, s.propNames()))
}

// ---------------------------------------------------------------------------
// required
// ---------------------------------------------------------------------------

// Required REPLACES the required set with exactly keys. Every key must exist.
//
// The emitted `required` list follows PROPERTY order, not the caller's argument
// order — the IR derives the list from the Prop.Required flags.
func (s Schema) Required(keys ...string) Schema {
	props := make([]*Prop, 0, len(keys))
	for _, k := range keys {
		props = append(props, s.mustProp(k))
	}
	n := s.object()
	for i := range n.Props {
		n.Props[i].Required = false
	}
	for _, p := range props {
		p.Required = true
	}
	return s
}

// RequireAlso ADDS keys to the existing required set, leaving the current
// members in place. Every key must exist in properties.
//
// This is the additive counterpart of Required, which REPLACES. Reach for it
// whenever the current set was not written literally at the call site — e.g.
// after a merge that builds a required UNION: calling Required there silently
// discards that union and leaves a component with one required key, a failure
// invisible to tests that compare against a document regenerated by the same
// code path.
func (s Schema) RequireAlso(keys ...string) Schema {
	for _, k := range keys {
		s.mustProp(k).Required = true
	}
	return s
}

// Optional removes keys from required. Keys must exist in properties (typo
// guard); removing a non-required key is a no-op.
func (s Schema) Optional(keys ...string) Schema {
	for _, k := range keys {
		s.mustProp(k).Required = false
	}
	return s
}

// RequiredAll marks every current property required.
//
// The emitted list follows Props order: for a RawFragment-built object that is
// sorted key order, for a reflected object it is field order.
func (s Schema) RequiredAll() Schema {
	n := s.object()
	for i := range n.Props {
		n.Props[i].Required = true
	}
	return s
}

// ---------------------------------------------------------------------------
// per-property deltas
// ---------------------------------------------------------------------------

// Nullable folds "null" into each key using the canonical OAS-3.1 idiom for the
// node's shape: scalar/enum/array/object → type-array (an enum also gains a
// null member); bare $ref → anyOf[$ref, null]; anyOf/oneOf → a null arm appended
// to the existing arms; allOf → the whole allOf WRAPPED as one arm of a new
// anyOf beside null (appending null to an allOf would demand the value be null
// AND everything else). Idempotent.
func (s Schema) Nullable(keys ...string) Schema {
	for _, k := range keys {
		p := s.mustProp(k)
		if p.Schema.Kind == KindOpaque {
			// irNullable cannot transform bytes it does not understand, and a
			// silent no-op is exactly what this DSL must never do. Wrap instead;
			// the result is a combinator, so a second call is idempotent through
			// the normal path.
			p.Schema = AnyOfNull(Schema{n: p.Schema}).n
			continue
		}
		p.Schema = irNullable(p.Schema)
	}
	return s
}

// NoFormat drops the format annotation.
func (s Schema) NoFormat(keys ...string) Schema {
	for _, k := range keys {
		s.mustProp(k).Schema.Format = ""
	}
	return s
}

// Ref REPLACES a property with a bare $ref to a named component.
func (s Schema) Ref(key, component string) Schema {
	s.mustProp(key).Schema = newRef(component)
	return s
}

// Enum REPLACES a property with a string enum over values.
func (s Schema) Enum(key string, values ...string) Schema {
	s.mustProp(key).Schema = newEnum("string", false, stringsToAny(values)...)
	return s
}

// NullableEnum REPLACES a property with a nullable string enum: "null" joins
// both the type list AND the enum members — without the null member the enum,
// the stricter of the two constraints, would make the null type unreachable.
func (s Schema) NullableEnum(key string, values ...string) Schema {
	s.mustProp(key).Schema = newEnum("string", true, stringsToAny(values)...)
	return s
}

// Describe sets a property's description.
func (s Schema) Describe(key, text string) Schema {
	p := s.mustProp(key)
	if p.Schema.Kind == KindOpaque {
		panic(fmt.Sprintf("apidoc: Describe(%q): property is an opaque fragment; put the description inside it", key))
	}
	p.Schema.Description = text
	return s
}

func stringsToAny(values []string) []any {
	out := make([]any, len(values))
	for i, v := range values {
		out[i] = v
	}
	return out
}

// OpenObject removes additionalProperties, leaving the object open.
func (s Schema) OpenObject() Schema {
	if s.n != nil {
		s.n.AdditionalProperties = nil
	}
	return s
}

// Pick projects properties onto keys (variant-view base); required follows the
// surviving keys. Surviving properties keep their relative order.
func (s Schema) Pick(keys ...string) Schema {
	keep := map[string]bool{}
	for _, k := range keys {
		s.mustProp(k)
		keep[k] = true
	}
	s.filterProps(func(name string) bool { return keep[name] })
	return s
}

// Omit drops keys from properties; required follows.
func (s Schema) Omit(keys ...string) Schema {
	drop := map[string]bool{}
	for _, k := range keys {
		s.mustProp(k)
		drop[k] = true
	}
	s.filterProps(func(name string) bool { return !drop[name] })
	return s
}

func (s Schema) filterProps(keep func(string) bool) {
	n := s.object()
	next := make([]Prop, 0, len(n.Props))
	for _, p := range n.Props {
		if keep(p.Name) {
			next = append(next, p)
		}
	}
	n.Props = next
}

// ---------------------------------------------------------------------------
// Set
// ---------------------------------------------------------------------------

// Set is the enumerated escape hatch: a dotted path into the typed IR.
//
// Structural segments walk the node graph — "properties.<name>" descends into a
// property, "items" into an array's element schema, "anyOf.<i>"/"oneOf.<i>"/
// "allOf.<i>" into a combinator arm. The FINAL segment lands in its typed field
// (with a value-type check) or, for an "x-" key, in Extensions. A final
// "properties.<name>" naming a NEW property upserts it — the value may be a
// fragment map or a Schema, whose IR node is spliced in directly.
//
// Every failure panics at declaration time: an unresolvable path, a mistyped
// value, or a standard keyword outside the IR's typed set.
func (s Schema) Set(path string, v any) Schema {
	segs := strings.Split(path, ".")
	if s.n == nil {
		panic(fmt.Sprintf("apidoc: Set(%q): schema is empty", path))
	}
	setPath(s.n, path, segs, v)
	return s
}

func setPath(cur *IRNode, path string, segs []string, v any) {
	if cur == nil {
		panic(fmt.Sprintf("apidoc: Set(%q): path runs past a missing schema", path))
	}
	if cur.Kind == KindOpaque {
		panic(fmt.Sprintf("apidoc: Set(%q): cannot address inside an opaque fragment", path))
	}
	seg := segs[0]

	switch seg {
	case "properties":
		if cur.Kind != KindObject {
			panic(fmt.Sprintf("apidoc: Set(%q): segment %q: node is a %s, not an object", path, seg, cur.Kind))
		}
		if len(segs) < 2 {
			panic(fmt.Sprintf("apidoc: Set(%q): %q needs a property name", path, seg))
		}
		name := segs[1]
		idx := -1
		for i := range cur.Props {
			if cur.Props[i].Name == name {
				idx = i
				break
			}
		}
		if len(segs) == 2 {
			// Final segment: replace or UPSERT (a reflector may emit no property
			// at all for an `any`-typed field).
			child := setValueNode(path, v)
			if idx >= 0 {
				cur.Props[idx].Schema = child
			} else {
				cur.Props = append(cur.Props, Prop{Name: name, Schema: child})
			}
			return
		}
		if idx < 0 {
			panic(fmt.Sprintf("apidoc: Set(%q): unknown property %q in schema (have %v)", path, name, Schema{n: cur}.propNames()))
		}
		setPath(cur.Props[idx].Schema, path, segs[2:], v)
		return

	case "anyOf", "oneOf", "allOf":
		arms := cur.AnyOf
		switch seg {
		case "oneOf":
			arms = cur.OneOf
		case "allOf":
			arms = cur.AllOf
		}
		if len(segs) == 1 {
			break // leaf: fall through to the keyword setter
		}
		i, err := strconv.Atoi(segs[1])
		if err != nil {
			panic(fmt.Sprintf("apidoc: Set(%q): %q needs an arm index, got %q", path, seg, segs[1]))
		}
		if i < 0 || i >= len(arms) {
			panic(fmt.Sprintf("apidoc: Set(%q): %s index %d is out of range (%d arms)", path, seg, i, len(arms)))
		}
		if len(segs) == 2 {
			arms[i] = setValueNode(path, v)
			return
		}
		setPath(arms[i], path, segs[2:], v)
		return

	case "items":
		if len(segs) == 1 {
			break // leaf: fall through to the keyword setter
		}
		if cur.Items == nil {
			panic(fmt.Sprintf("apidoc: Set(%q): node has no items schema", path))
		}
		setPath(cur.Items, path, segs[1:], v)
		return

	case "not":
		if len(segs) == 1 {
			break
		}
		if cur.Not == nil {
			panic(fmt.Sprintf("apidoc: Set(%q): node has no not schema", path))
		}
		setPath(cur.Not, path, segs[1:], v)
		return
	}

	if len(segs) != 1 {
		panic(fmt.Sprintf("apidoc: Set(%q): segment %q does not address a schema", path, seg))
	}
	if err := assignKeyword(cur, seg, v); err != nil {
		panic(fmt.Sprintf("apidoc: Set(%q): %s", path, err))
	}
	if err := cur.checkInvariants(); err != nil {
		panic(fmt.Sprintf("apidoc: Set(%q): %s", path, err))
	}
}

// setValueNode turns a Set value into a node: a Schema splices its IR directly
// (composition without RefPrefix string concatenation), a map is parsed like a
// RawFragment.
func setValueNode(path string, v any) *IRNode {
	// STRICT: Set is a typed ingress path, so an exotic fragment is an error
	// here rather than a silent Opaque. RawFragment is where exotica belongs.
	n, err := fragChild(v, true)
	if err != nil {
		panic(fmt.Sprintf("apidoc: Set(%q): mistyped value: %s", path, err))
	}
	if n == nil {
		panic(fmt.Sprintf("apidoc: Set(%q): mistyped value: schema is nil", path))
	}
	return n
}

// ---------------------------------------------------------------------------
// keyword assignment (shared by fragmentToIR and Set)
// ---------------------------------------------------------------------------

func mistyped(key, want string, v any) error {
	return fmt.Errorf("mistyped value for %q: want %s, got %T", key, want, v)
}

// assignKeyword writes one keyword into its typed field, with a value-type
// check. "x-" keys land in Extensions; a standard keyword the IR does not model
// (and any other unknown key) is rejected — the typed ingress paths refuse
// exotica, RawFragment is where an opaque fragment belongs.
func assignKeyword(n *IRNode, key string, v any) error {
	if strings.HasPrefix(key, "x-") {
		// SetExtension is the ONE implementation: it validates the key and
		// re-collects extRefs over the whole map, so components assembly's
		// dangling-ref check sees a "$ref" hiding inside an extension value no
		// matter which writer put it there.
		return n.SetExtension(key, v)
	}

	switch key {
	case "$ref":
		s, ok := v.(string)
		if !ok {
			return mistyped(key, "string", v)
		}
		n.Ref = strings.TrimPrefix(s, RefPrefix)
		return nil

	case "type":
		types, err := fragTypes(v)
		if err != nil {
			return fmt.Errorf("mistyped value for %q: %w", key, err)
		}
		n.Types = types
		return nil

	case "enum":
		vals, ok := v.([]any)
		if !ok {
			return mistyped(key, "[]any", v)
		}
		n.Enum = append([]any(nil), vals...)
		if n.Kind == KindScalar {
			n.Kind = KindEnum
		}
		return nil

	case "required":
		if n.Kind != KindObject {
			return fmt.Errorf(`"required" needs an object node, got %s`, n.Kind)
		}
		names, err := fragStrings(v)
		if err != nil {
			return fmt.Errorf("mistyped value for %q: %w", key, err)
		}
		for i := range n.Props {
			n.Props[i].Required = false
		}
		return fragApplyRequired(n, names)

	case "items":
		child, err := fragChild(v, true)
		if err != nil {
			return fmt.Errorf("mistyped value for %q: %w", key, err)
		}
		n.Items = child
		return nil

	case "not":
		child, err := fragChild(v, true)
		if err != nil {
			return fmt.Errorf("mistyped value for %q: %w", key, err)
		}
		n.Not = child
		return nil

	case "additionalProperties":
		ap, err := fragAdditionalProperties(v, true)
		if err != nil {
			return fmt.Errorf("mistyped value for %q: %w", key, err)
		}
		n.AdditionalProperties = ap
		return nil

	case "properties", "anyOf", "oneOf", "allOf":
		return fmt.Errorf("%q must be addressed one member at a time (e.g. %s.<member>)", key, key)

	case "const":
		n.Const = v
		return nil
	case "default":
		n.Default = v
		return nil
	case "examples":
		vals, ok := v.([]any)
		if !ok {
			return mistyped(key, "[]any", v)
		}
		n.Examples = append([]any(nil), vals...)
		return nil
	case "dependentRequired":
		dr, ok := v.(map[string][]string)
		if !ok {
			return mistyped(key, "map[string][]string", v)
		}
		n.DependentRequired = dr
		return nil
	}

	if target, ok := stringField(n, key); ok {
		s, ok := v.(string)
		if !ok {
			return mistyped(key, "string", v)
		}
		*target = s
		return nil
	}
	if target, ok := boolField(n, key); ok {
		b, ok := v.(bool)
		if !ok {
			return mistyped(key, "bool", v)
		}
		*target = b
		return nil
	}
	if target, ok := floatField(n, key); ok {
		f, ok := toFloat(v)
		if !ok {
			return mistyped(key, "number", v)
		}
		*target = &f
		return nil
	}
	if target, ok := intField(n, key); ok {
		i, ok := toInt(v)
		if !ok {
			return mistyped(key, "integer", v)
		}
		*target = &i
		return nil
	}

	if standardKeywords[key] {
		return fmt.Errorf("standard keyword %q is outside the typed set", key)
	}
	return fmt.Errorf("keyword %q is outside the typed set (only x- extensions may be unknown)", key)
}

func stringField(n *IRNode, key string) (*string, bool) {
	switch key {
	case "pattern":
		return &n.Pattern, true
	case "format":
		return &n.Format, true
	case "description":
		return &n.Description, true
	case "title":
		return &n.Title, true
	case "contentEncoding":
		return &n.ContentEncoding, true
	case "contentMediaType":
		return &n.ContentMediaType, true
	}
	return nil, false
}

func boolField(n *IRNode, key string) (*bool, bool) {
	switch key {
	case "uniqueItems":
		return &n.UniqueItems, true
	case "readOnly":
		return &n.ReadOnly, true
	case "writeOnly":
		return &n.WriteOnly, true
	case "deprecated":
		return &n.Deprecated, true
	}
	return nil, false
}

func floatField(n *IRNode, key string) (**float64, bool) {
	switch key {
	case "minimum":
		return &n.Minimum, true
	case "maximum":
		return &n.Maximum, true
	case "exclusiveMinimum":
		return &n.ExclusiveMinimum, true
	case "exclusiveMaximum":
		return &n.ExclusiveMaximum, true
	case "multipleOf":
		return &n.MultipleOf, true
	}
	return nil, false
}

func intField(n *IRNode, key string) (**int, bool) {
	switch key {
	case "minLength":
		return &n.MinLength, true
	case "maxLength":
		return &n.MaxLength, true
	case "minItems":
		return &n.MinItems, true
	case "maxItems":
		return &n.MaxItems, true
	case "minProperties":
		return &n.MinProperties, true
	case "maxProperties":
		return &n.MaxProperties, true
	}
	return nil, false
}

// toFloat accepts any Go numeric: hand-written fragments carry ints, JSON round
// trips carry float64. The check is KIND-based, so a named numeric type passes
// too; uintptr does not — it is an address, not a number.
func toFloat(v any) (float64, bool) {
	rv := reflect.ValueOf(v)
	if rv.Kind() == reflect.Uintptr {
		return 0, false
	}
	switch {
	case rv.CanInt():
		return float64(rv.Int()), true
	case rv.CanUint():
		return float64(rv.Uint()), true
	case rv.CanFloat():
		return rv.Float(), true
	}
	return 0, false
}

// toInt accepts any Go integer and an integral float (JSON has no int type).
func toInt(v any) (int, bool) {
	f, ok := toFloat(v)
	if !ok {
		return 0, false
	}
	i := int(f)
	if float64(i) != f {
		return 0, false
	}
	return i, true
}

// ---------------------------------------------------------------------------
// constructors / combinators
// ---------------------------------------------------------------------------

// RefTo is a bare $ref to a named component.
func RefTo(component string) Schema { return Schema{n: newRef(component)} }

// AllOf composes parts by reference (single-owner convention).
func AllOf(parts ...Schema) Schema { return Schema{n: newAllOf(armNodes("AllOf", parts)...)} }

// OneOf composes parts by reference (sum-type document arm; the status and
// marshalling half of a sum type lives in the application's operation layer).
func OneOf(parts ...Schema) Schema { return Schema{n: newOneOf(armNodes("OneOf", parts)...)} }

// AnyOf composes parts by reference (polymorphic whole-body or restricted-arm
// document, as used by BodySchemaProvider bodies).
func AnyOf(parts ...Schema) Schema { return Schema{n: newAnyOf(armNodes("AnyOf", parts)...)} }

func armNodes(verb string, parts []Schema) []*IRNode {
	out := make([]*IRNode, len(parts))
	for i, p := range parts {
		if p.n == nil {
			panic(fmt.Sprintf("apidoc: %s: part %d is an empty Schema", verb, i))
		}
		out[i] = p.n
	}
	return out
}

// AnyOfNull composes anyOf[inner, {type:"null"}], for building nullable inline
// objects and enums passed to Set. Idempotent: if inner is already an anyOf
// carrying a null arm, it is returned unchanged.
func AnyOfNull(inner Schema) Schema {
	if inner.n == nil {
		panic("apidoc: AnyOfNull: empty Schema")
	}
	if inner.n.Kind == KindCombinator && hasNullArm(inner.n.AnyOf) {
		return inner
	}
	return Schema{n: newAnyOf(inner.n, newScalar("null"))}
}

// AnyOfNull rewrites each named property to anyOf[<current>, {type:null}] — the
// form reflected enums, $refs and inline objects take in the committed document.
func (s Schema) AnyOfNull(keys ...string) Schema {
	for _, k := range keys {
		p := s.mustProp(k)
		p.Schema = AnyOfNull(Schema{n: p.Schema}).n
	}
	return s
}
